site_name: Harsh's Tech Notes
markdown_extensions:
  - attr_list
  - md_in_html
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.share
    - navigation.footer
  icon: 
    # logo: fontawesome/solid/brain
    logo: fontawesome/solid/layer-group
  font:
    text: Raleway
    # text: Open Sans
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - tags:
      tags_file : tags.md
  - search:

# Page tree
nav:
  - Cloud: 
    - Cloud Computing: Cloud/cloud-computing.md
# # Page tree
# nav:
#   - Home: index.md
#   - Getting started:
#     - Installation: getting-started.md
#     - Creating your site: creating-your-site.md
#     - Bug reporting:
#       - bug-report/index.md
#       - Creating a reproduction: bug-report/reproduction.md
#     - Changelog:
#       - changelog/index.md
#       - How to upgrade: upgrade.md
#   - Setup:
#     - Changing the colors: setup/changing-the-colors.md
#     - Changing the fonts: setup/changing-the-fonts.md
#     - Extensions:
#       - setup/extensions/index.md
#       - Python Markdown: setup/extensions/python-markdown.md